run_turnoffon:
  description: This can be used to dynamically set the date and/or time.
  fields:
    entity_id: {description: Entity id of the input datetime to set the new value.,
      example: input_datetime.test_date_time}
set_time:
  description: This can be used to dynamically set the date and/or time.
  fields:
    entity_id: {description: Entity id of the input datetime to set the new value.,
      example: input_datetime.test_date_time}
    zacatek: {description: Entity id of the input datetime to set the new value.,
      example: input_datetime.test_date_time}
    konec: {description: Entity id of the input datetime to set the new value.,
      example: input_datetime.test_date_time}
    delka: {description: Entity id of the input datetime to set the new value.,
      example: input_datetime.test_date_time}